### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by kllelndhlm** [ereborinkorppi/tiralabra#2]
Repositorio kloonattu 27.8.2022 klo 19:56

Koodia on helppo seurata, ja se on myös hyvin kommentoitu. Kummankin pakkausmenetelmän käyttö toimii manuaalisen testauksen perusteella. Testeistä yksi ei mennyt läpi. Lint näyttää koodin laaduksi 10/10. Testausdokumentaatio on selkeää. Projekti vaikuttaa olevan hyvällä mallilla.

**Comment by ereborinkorppi** [comment]
Kiitos palautteesta. Olisitko vielä voinut selventää mikä testi ei mene läpi? Minulla omassa setupissa toimii kaikki testit.

**Comment by kllelndhlm** [comment]
Testien suorittaminen tuolla 27.8. klo 19:56 kloonatulla repositoriolla antoi seuraavan virheilmoituksen:
```bash
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/kazlindh/tiralabra
collected 5 items

src/tests/huffman_algo_test.py ...                                       [ 60%]
src/tests/lz_seventyeight_test.py F.                                     [100%]

=================================== FAILURES ===================================
_______________________ TestLzSeventyeight.test_compress _______________________

self = <tests.lz_seventyeight_test.TestLzSeventyeight testMethod=test_compress>

    def test_compress(self):
>       self.assertEqual(self.lz_seventyeight_compress.compress(),
                         b'\x80\x03]q\x00(X\x01\x00\x00\x00Aq\x01M\x00\x01X\x01\x00\x00\x00Bq\x02h\x02X\x01\x00\x00\x00Cq\x03e.')
E       AssertionError: bytearray(b'\x80\x04\x95\x16\x00\x00\x00\x[72 chars]4e.') != b'\x80\x03]q\x00(X\x01\x00\x00\x00Aq\x01M\[56 chars]03e.'

src/tests/lz_seventyeight_test.py:12: AssertionError
=========================== short test summary info ============================
FAILED src/tests/lz_seventyeight_test.py::TestLzSeventyeight::test_compress
========================= 1 failed, 4 passed in 0.06s ==========================
```
Pahoittelut epäselvyydestä.

**Comment by ereborinkorppi** [comment]
Kiitos, erikoista tosiaan tuolla koneella jolla olen tätä tehnyt tämäkin testi menee läpi, mutta itselläni tulee sama ongelma kun kokeilen toisella koneella. Jos taas vaihdan tätä, niin tämä testi ei mene enää läpi sillä koneella jolla projektia teen.
